stages:
  - build
  - style_test
  - test
  - deploy

build-job:
  stage: build
  script: 
    - cd src/cat && make
    - cd ../grep && make
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  only:
    - develop
  after_script:
          - bash src/part6.sh 

codestyle:
  stage: style_test
  script:
    - cp materials/linters/.clang-format src/
    - clang-format -n -Werror src/*/*.c
  only:
    - develop
  after_script:
          - bash src/part6.sh 

Test:
  stage: test
  script:
    - cd src/cat && chmod +x test_func_cat.sh && bash test_func_cat.sh
    - cd ../grep && chmod +x tests_big.sh && bash tests_big.sh
  only:
    - develop
  after_script:
          - bash src/part6.sh 

deploy:
  stage: deploy
  script:
      - cd src
      - bash deploy.sh
  only:
    - develop
  after_script:
          - bash src/part6.sh 